name: Deploy Backend to AWS EC2 on PR

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Pull project
        script: |
          cd playable-case/be
          git pull origin main

      - name: Create .env on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            touch .env
            echo "ACCESS_TOKEN_SECRET_KEY=${{ secrets.ACCESS_TOKEN_SECRET_KEY }}" > /home/ec2-user/playable-case/be/.env
            echo "REFRESH_TOKEN_SECRET_KEY=${{ secrets.REFRESH_TOKEN_SECRET_KEY }}" >> /home/ec2-user/playable-case/be/.env
            echo "ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }}" >> /home/ec2-user/playable-case/be/.env
            echo "REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }}" >> /home/ec2-user/playable-case/be/.env
            echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> /home/ec2-user/playable-case/be/.env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> /home/ec2-user/playable-case/be/.env
            echo "PORT=${{ secrets.PORT }}" >> /home/ec2-user/playable-case/be/.env
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> /home/ec2-user/playable-case/be/.env
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> /home/ec2-user/playable-case/be/.env
            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> /home/ec2-user/playable-case/be/.env
            echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> /home/ec2-user/playable-case/be/.env
            echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> /home/ec2-user/playable-case/be/.env

      - name: Run Project
        script: |
          npm install
          npm run dev
          pm2 restart all

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/your/app
            git pull origin main
            npm install
            npm run build
            pm2 restart all